import "./globals.css";
import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"]);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" >

      <body className="min-h-full flex flex-col w-full mx-auto">
        <main className="w-full mx-auto">  {children}</main>

      </body>
    </html>
  );
}
